# Generated by Django 4.2.11 on 2024-04-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("controller_type", models.CharField(max_length=200)),
                (
                    "controller_name",
                    models.CharField(max_length=200, verbose_name="controller name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sv", models.IntegerField(default=120)),
                ("const_P", models.IntegerField(default=30)),
                ("const_I", models.IntegerField(default=240)),
                ("const_D", models.IntegerField(default=60)),
                ("do_ARW", models.BooleanField(default=False)),
                (
                    "controller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstsimulator.controller",
                    ),
                ),
            ],
        ),
    ]
