# Generated by Django 4.2.11 on 2024-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstsimulator", "0002_plant_rename_parameter_contparameter_plantparameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataForPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TimeForPlot", models.IntegerField()),
                ("PVForPlot", models.IntegerField()),
            ],
        ),
    ]
